### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by TimFelix** [ARCANEDEV/LaravelAuth#25]
- LaravelAuth Version: 2.2
- Laravel Version: 5.4
- PHP Version: 7.1.4

### Description:

Hi arcanedev-maroc.
This package looks awesome.

I followed the installation steps successfully.
So it seems to have installed correctly. I'm just not clear on the usage.
Should i build the forms and views myself?
If there's any examples out there I'd love to see them.

Thanks for any guidance.

**Comment by arcanedev-maroc** [comment]
Hi @TimFelix,

If you ask about the usage, you can start by check the [tests folder](https://github.com/ARCANEDEV/LaravelAuth/tree/master/tests) to see all the available features.

This package contains only the logic to manage your auth layer, it doesn't have any UI, route, controller etc

You can check this `Auth` module for `ARCANESOFT` CMS that uses this package, it's a little bit advanced but you're going to find everything you need (Routes, Controllers, Form Request, Policies ...): https://github.com/ARCANESOFT/Auth

Hope this helps you
