### ISSUE TITLE
Finalising documentation

### ISSUE THREAD

**Issue by bretto36** [ARCANEDEV/LaravelAuth#7]
Any chance you can give a run down on what else needs to be set up to use this. I've added it to my project. How do i go about removing all the previous Auth stuff so it references this Auth system

**Comment by arcanedev-maroc** [comment]
Hi @bretto36, thanks for using this package.

As you can see, this package is WIP, please don't use this for production right now.

This package is only supported by Laravel 5.1, you can start by editing the [auth.php file](https://github.com/laravel/laravel/blob/5.1/config/auth.php#L31) with this [value](https://github.com/ARCANEDEV/LaravelAuth/blob/master/tests/TestCase.php#L62).

You can also check the `tests` folder for more usage details, for example : [The Auth Models](https://github.com/ARCANEDEV/LaravelAuth/tree/master/tests/Models)

**Comment by bretto36** [comment]
Ah i didn't even think to look at the tests! Thank you. Keep up the good work. It's a really good package
